# Generated by Django 2.1.1 on 2018-09-02 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='data',
        ),
    ]
